export const data = [
  {
    id: 1,
    Name: 'Join w/ Annual Site Free',
    Description: 'Join w/ Annual Free for Website',
    ConsultantType: 'Consultant',
    ConsultantRankType: 'Consultant',
    ConsultantStatus: 'Active',
    PersonalWebsite: 'Yes',
    PortalAcess: 'Yes',
    HasSubscriptions: 'Yes',
  },
  {
    id: 2,
    Name: '4 Bottle Club',
    Description: 'Join 4 Bottle Wine Club',
    ConsultantType: 'Circle Consultant',
    ConsultantRankType: 'Consultant',
    ConsultantStatus: 'Active',
    PersonalWebsite: 'No',
    PortalAcess: 'Yes',
    HasSubscriptions: 'Yes',
  },
  {
    id: 3,
    Name: '4 Bottle Club',
    Description: 'Join 4 Bottle Wine Club',
    ConsultantType: 'Circle Consultant',
    ConsultantRankType: 'Consultant',
    ConsultantStatus: 'Active',
    PersonalWebsite: 'No',
    PortalAcess: 'Yes',
    HasSubscriptions: 'Yes',
  },
]
